/*
 * QUADLUD — Rectangles inference engine
 * Copyright © 2026 Serge Benoliel. All rights reserved.
 * Proprietary software. Copying, modification, redistribution or exploitation
 * without prior written authorization is prohibited.
 */
(function(root){
'use strict';

const RULE_COST={
  RECTANGLE_DOMAIN:0,CLUE_SINGLETON:0,CELL_SINGLETON:0,RECTANGLE_PROPAGATION:0,
  OWNERSHIP_PROPAGATION:0,RECTANGULAR_CLOSURE:0,AREA_COMPLETION:0,
  COMMON_COVERAGE:1,CELL_LOCKED_TO_CLUE:1,COVERAGE_LOCKED_SET:1,
  NO_SUPPORT_CLUE:1,NO_SUPPORT_CELL:1,LOCAL_DOMAIN_SUPPORT:1,
  ASSUMPTION_CONTRADICTION:2,COMMON_CONSEQUENCE:2
};
const TECHNIQUE_LEVEL={T0:0,T1:1,T2:2,T3:3};
const RULE_LEVEL={
  RECTANGLE_DOMAIN:0,CLUE_SINGLETON:0,CELL_SINGLETON:0,RECTANGLE_PROPAGATION:0,
  OWNERSHIP_PROPAGATION:0,RECTANGULAR_CLOSURE:0,AREA_COMPLETION:0,
  COMMON_COVERAGE:1,CELL_LOCKED_TO_CLUE:1,COVERAGE_LOCKED_SET:2,
  NO_SUPPORT_CLUE:2,NO_SUPPORT_CELL:2,LOCAL_DOMAIN_SUPPORT:2,
  ASSUMPTION_CONTRADICTION:3,COMMON_CONSEQUENCE:3
};
const RULE_PRIORITY={
  CLUE_SINGLETON:0,CELL_SINGLETON:5,RECTANGULAR_CLOSURE:8,AREA_COMPLETION:9,
  COMMON_COVERAGE:10,CELL_LOCKED_TO_CLUE:20,COVERAGE_LOCKED_SET:30,
  NO_SUPPORT_CLUE:40,NO_SUPPORT_CELL:45,LOCAL_DOMAIN_SUPPORT:60,
  ASSUMPTION_CONTRADICTION:90,COMMON_CONSEQUENCE:100
};

function copy(x){return JSON.parse(JSON.stringify(x))}
function cellKey(c){return c[0]+','+c[1]}
function rectKey(r){return `${r.r0},${r.c0},${r.r1},${r.c1}`}
function sameCell(a,b){return !!a&&!!b&&a[0]===b[0]&&a[1]===b[1]}
function uniq(a){return [...new Set((a||[]).filter(x=>x!=null))]}
function uniqCells(a){let s=new Set(),o=[];for(const c of a||[]){if(!Array.isArray(c))continue;let k=cellKey(c);if(!s.has(k)){s.add(k);o.push(c.slice())}}return o}
function maxRank(ps){let a=(ps||[]).map(p=>Number(p?.rank)||0);return a.length?Math.max(...a):0}
function combinations(items,k){let out=[];function go(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=items.length-(k-p.length);j++){p.push(items[j]);go(j+1,p);p.pop()}}go(0,[]);return out}
function rectCells(r){let out=[];for(let rr=r.r0;rr<=r.r1;rr++)for(let c=r.c0;c<=r.c1;c++)out.push([rr,c]);return out}
function rectHas(r,cell){return cell[0]>=r.r0&&cell[0]<=r.r1&&cell[1]>=r.c0&&cell[1]<=r.c1}
function rectOverlap(a,b){return !(a.r1<b.r0||b.r1<a.r0||a.c1<b.c0||b.c1<a.c0)}
function shapeOf(h,w){return h===w?'square':h>w?'vertical':'horizontal'}
function normalizeShape(s){if(s==null||s==='none'||s==='?'||s==='libre')return null;if(s==='carré'||s==='square'||s==='□')return 'square';if(s==='vertical'||s==='▯')return 'vertical';if(s==='horizontal'||s==='▭')return 'horizontal';return s}
function clueConstraints(clue){let mode=clue?.mode??null,area=null,shape=null;if(mode==='both'||mode==='size')area=Number(clue.size);else if(mode==null&&Number.isFinite(Number(clue.area)))area=Number(clue.area);if(mode==='both'||mode==='shape')shape=normalizeShape(clue.shape);else if(mode==null)shape=normalizeShape(clue.shape);return {area:Number.isFinite(area)&&area>0?area:null,shape}}
function keyOrRect(r){return r.key||rectKey(r)}
function rectFromCells(cells){if(!cells?.length)return null;let rs=cells.map(x=>x[0]),cs=cells.map(x=>x[1]);return {r0:Math.min(...rs),r1:Math.max(...rs),c0:Math.min(...cs),c1:Math.max(...cs)}}
function deductionComparator(a,b){return (a.rank-b.rank)||(a.techniqueLevel-b.techniqueLevel)||((a.priority??50)-(b.priority??50))||((a.focusCells?.length||0)-(b.focusCells?.length||0))||String(a.signature||a.id).localeCompare(String(b.signature||b.id))}
function traceDependencyIds(d){return uniq([...(d?.dependencies||[]),...(d?.premises||[]).flatMap(p=>p?.dependencies||[])])}
function causalTraceFromIds(trace,seedIds){let list=trace||[],byId=new Map(list.map(d=>[d.id,d])),need=new Set((seedIds||[]).filter(id=>byId.has(id))),stack=[...need];while(stack.length){let d=byId.get(stack.pop());if(!d)continue;for(const id of traceDependencyIds(d))if(byId.has(id)&&!need.has(id)){need.add(id);stack.push(id)}}return list.filter(d=>need.has(d.id)).map(copy)}
function sameConclusion(a,b){if(!a||!b||a.type!==b.type)return false;if(a.type==='OWNER')return sameCell(a.cell,b.cell)&&Number(a.clue)===Number(b.clue);if(a.type==='SELECTED_RECT')return Number(a.clue)===Number(b.clue)&&keyOrRect(a.rectangle)===keyOrRect(b.rectangle);if(a.type==='ELIMINATED_CANDIDATE')return Number(a.clue)===Number(b.clue)&&a.rectangleKey===b.rectangleKey;if(a.type==='NOT_OWNER')return sameCell(a.cell,b.cell)&&Number(a.clue)===Number(b.clue);return false}
function causalTraceForConclusion(trace,conclusion){let seeds=(trace||[]).filter(d=>(d.conclusions||[]).some(c=>sameConclusion(c,conclusion))).map(d=>d.id);return seeds.length?causalTraceFromIds(trace,seeds):(trace||[]).map(copy)}
function causalTraceForWitness(trace,witness){let seeds=(witness?.premises||[]).flatMap(p=>p?.dependencies||[]);return seeds.length?causalTraceFromIds(trace,seeds):(trace||[]).map(copy)}

function normalizeBoard(board){
  if(!board||!Number.isInteger(board.n)||board.n<5||board.n>10)throw new Error('Rectangles size must be an integer from 5 to 10');
  let ids=Array.isArray(board.ids)?board.ids.slice():Object.keys(board.clues||{}).map(x=>Number.isNaN(Number(x))?x:Number(x));
  if(!ids.length||!board.clues)throw new Error('Rectangles clues are required');
  let clues={};for(const id of ids){let raw=board.clues[id],pos=raw?.pos;if(!Array.isArray(pos)||pos.length!==2||!pos.every(Number.isInteger)||pos[0]<0||pos[0]>=board.n||pos[1]<0||pos[1]>=board.n)throw new Error('Invalid Rectangles clue position');let q=clueConstraints(raw);clues[id]={id,pos:pos.slice(),area:q.area,shape:q.shape,raw:copy(raw)}}
  let seen=new Set();for(const id of ids){let k=cellKey(clues[id].pos);if(seen.has(k))throw new Error('Two clues cannot share a cell');seen.add(k)}
  let paint=Array.isArray(board.paint)?board.paint.map(r=>r.slice()):Array.from({length:board.n},()=>Array(board.n).fill(null));
  if(paint.length!==board.n||paint.some(r=>!Array.isArray(r)||r.length!==board.n))throw new Error('Invalid Rectangles paint dimensions');
  let selectedRects=board.selectedRects&&typeof board.selectedRects==='object'?copy(board.selectedRects):{};
  let logicEvidence=board.logicEvidence&&typeof board.logicEvidence==='object'?copy(board.logicEvidence):{schema:1,owners:[],notOwners:[],selected:[],eliminated:[]};
  return {n:board.n,ids,clues,paint,selectedRects,logicEvidence};
}

class Session{
  constructor(board,options={}){
    let b=normalizeBoard(board);this.n=b.n;this.ids=b.ids;this.clues=b.clues;this.paint=b.paint;this.visibleSelectedRects=b.selectedRects||{};this.visibleLogicEvidence=b.logicEvidence||{};
    this.options={maxLockedSetSize:3,maxLockedSetClues:12,maxLocalGroupSize:3,maxLocalCandidates:120,maxHypothesisCandidates:5,maxHypothesisSteps:14,maxCommonSteps:8,...options};
    this.factSeq=0;this.dedSeq=0;this.ownerFacts=new Map();this.notOwnerFacts=new Map();this.selected=new Map();this.candidates=new Map();this.candidateIndex=new Map();this.activeCandidatesCache=new Map();this.domainPremiseCache=new Map();this.appliedDeductions=[];this.initialIssues=[];
    this.seedDomains();this.seedLogicEvidence();this.seedVisibleFacts();this.refreshDomains();this.seedMechanicalExclusions();
  }
  clone(){let x=Object.create(Session.prototype);x.n=this.n;x.ids=this.ids.slice();x.clues=copy(this.clues);x.paint=this.paint.map(r=>r.slice());x.visibleSelectedRects=copy(this.visibleSelectedRects||{});x.visibleLogicEvidence=copy(this.visibleLogicEvidence||{});x.options={...this.options};x.factSeq=this.factSeq;x.dedSeq=this.dedSeq;x.ownerFacts=new Map([...this.ownerFacts].map(([k,v])=>[k,copy(v)]));x.notOwnerFacts=new Map([...this.notOwnerFacts].map(([k,v])=>[k,copy(v)]));x.selected=new Map([...this.selected].map(([k,v])=>[k,copy(v)]));x.candidates=new Map([...this.candidates].map(([id,a])=>[id,a.map(copy)]));x.candidateIndex=new Map([...x.candidates].map(([id,a])=>[id,new Map(a.map(c=>[c.key,c]))]));x.activeCandidatesCache=new Map();x.domainPremiseCache=new Map();x.appliedDeductions=this.appliedDeductions.map(copy);x.initialIssues=this.initialIssues.map(copy);return x}
  clue(id){return this.clues[id]}
  candidate(id,key){return this.candidateIndex.get(id)?.get(key)||null}
  activeCandidates(id){let cached=this.activeCandidatesCache.get(id);if(cached)return cached;let active=(this.candidates.get(id)||[]).filter(x=>x.active);this.activeCandidatesCache.set(id,active);return active}
  activeCandidateKeys(id){return this.activeCandidates(id).map(x=>x.key)}
  owner(cell){return this.ownerFacts.get(cellKey(cell))||null}
  notOwner(cell,id){return this.notOwnerFacts.get(cellKey(cell)+'|'+id)||null}
  selectedRect(id){return this.selected.get(id)||null}
  domainRank(id){let rank=0,deps=[];for(const c of this.candidates.get(id)||[])if(!c.active&&c.elimination){rank=Math.max(rank,Number(c.elimination.rank)||0);deps.push(...(c.elimination.dependencies||[]));if(c.elimination.deductionId)deps.push(c.elimination.deductionId)}return {rank,dependencies:uniq(deps)}}
  domainPremise(id){let cached=this.domainPremiseCache.get(id);if(cached)return cached;let d=this.domainRank(id),p={kind:'CANDIDATE_SET',clue:id,remaining:this.activeCandidateKeys(id),rank:d.rank,dependencies:d.dependencies};this.domainPremiseCache.set(id,p);return p}
  factPremise(f){if(!f)return null;let p=copy(f);delete p.id;return p}
  makeFact(kind,data,meta={}){return {id:'F'+(++this.factSeq),kind,...copy(data),rank:Number(meta.rank)||0,source:meta.source||'deduction',deductionId:meta.deductionId||null,dependencies:uniq((meta.dependencies||[]).concat(meta.deductionId?[meta.deductionId]:[])),hypothesis:!!meta.hypothesis}}
  seedDomains(){
    let cluePositions=this.ids.map(id=>({id,pos:this.clues[id].pos}));
    for(const id of this.ids){let clue=this.clues[id],list=[],index=new Map();for(let r0=0;r0<this.n;r0++)for(let r1=r0;r1<this.n;r1++)for(let c0=0;c0<this.n;c0++)for(let c1=c0;c1<this.n;c1++){
      let rect={r0,r1,c0,c1},h=r1-r0+1,w=c1-c0+1,area=h*w,shape=shapeOf(h,w),reasons=[];
      if(!rectHas(rect,clue.pos))continue;
      for(const other of cluePositions)if(other.id!==id&&rectHas(rect,other.pos)){reasons.push('OTHER_CLUE_INSIDE');break}
      if(clue.area!=null&&area!==clue.area)reasons.push('WRONG_AREA');if(clue.shape&&shape!==clue.shape)reasons.push('WRONG_SHAPE');
      let key=rectKey(rect),cand={key,...rect,h,w,area,shape,cells:rectCells(rect),active:reasons.length===0,baseReasons:reasons,elimination:reasons.length?{rule:'RECTANGLE_DOMAIN',reason:reasons[0],reasons:reasons.slice(),rank:0,dependencies:[],source:'geometry'}:null};list.push(cand);index.set(key,cand)
    }this.candidates.set(id,list);this.candidateIndex.set(id,index)}
  }
  seedLogicEvidence(){
    let e=this.visibleLogicEvidence||{},meta=x=>({rank:Number(x?.rank)||0,dependencies:uniq(x?.dependencies||[]),deductionId:x?.deductionId||null,source:'deduction'});
    for(const x of e.eliminated||[])if(this.ids.includes(Number(x.clue)))this.eliminateCandidate(Number(x.clue),x.rectangleKey,{...meta(x),rule:x.rule||'RECTANGLE_DOMAIN',reason:x.reason||null,source:'deduction'});
    for(const x of e.owners||[])if(Array.isArray(x.cell)&&this.ids.includes(Number(x.clue)))this.addOwner(x.cell,Number(x.clue),meta(x));
    for(const x of e.notOwners||[])if(Array.isArray(x.cell)&&this.ids.includes(Number(x.clue)))this.addNotOwner(x.cell,Number(x.clue),meta(x));
    for(const x of e.selected||[]){let id=Number(x.clue),cand=this.candidate(id,x.rectangleKey);if(cand&&cand.active&&!this.selected.has(id))this.selected.set(id,this.makeFact('SELECTED_RECT',{clue:id,rect:copy(cand)},meta(x)))}
  }
  exportEvidence(){
    let dynamic=f=>f&&(f.deductionId||f.source==='deduction');
    return {schema:1,
      owners:[...this.ownerFacts.values()].filter(dynamic).map(f=>({cell:f.cell.slice(),clue:f.clue,rank:f.rank,dependencies:copy(f.dependencies||[]),deductionId:f.deductionId||null})),
      notOwners:[...this.notOwnerFacts.values()].filter(dynamic).map(f=>({cell:f.cell.slice(),clue:f.clue,rank:f.rank,dependencies:copy(f.dependencies||[]),deductionId:f.deductionId||null})),
      selected:[...this.selected.values()].filter(dynamic).map(f=>({clue:f.clue,rectangleKey:f.rect.key,rank:f.rank,dependencies:copy(f.dependencies||[]),deductionId:f.deductionId||null})),
      eliminated:[...this.candidates.entries()].flatMap(([clue,a])=>a.filter(c=>c.elimination&&(c.elimination.deductionId||c.elimination.source==='deduction')).map(c=>({clue,rectangleKey:c.key,rank:Number(c.elimination.rank)||0,dependencies:copy(c.elimination.dependencies||[]),deductionId:c.elimination.deductionId||null,rule:c.elimination.rule||'RECTANGLE_DOMAIN',reason:c.elimination.reason||null})))
    }
  }
  seedVisibleFacts(){
    // The clue cell always belongs to its own zone.
    for(const id of this.ids)this.addOwner(this.clues[id].pos,id,{rank:0,source:'clue'});
    // The player-visible painted state is input evidence, not a hidden solution.
    for(let r=0;r<this.n;r++)for(let c=0;c<this.n;c++){let id=this.paint[r][c];if(id==null)continue;if(!this.ids.includes(id)){this.initialIssues.push({kind:'OWNER_CONFLICT',cell:[r,c],clue:id,rank:0});continue}let ownClue=this.ids.find(x=>sameCell(this.clues[x].pos,[r,c]));if(ownClue!=null&&ownClue!==id)this.initialIssues.push({kind:'OTHER_CLUE_INSIDE',cell:[r,c],clue:id,otherClue:ownClue,rank:0});this.addOwner([r,c],id,{rank:0,source:'player'})}
    for(const id of this.ids){let raw=this.visibleSelectedRects?.[id];if(!raw)continue;let rect={r0:Number(raw.r0),r1:Number(raw.r1),c0:Number(raw.c0),c1:Number(raw.c1)};if(![rect.r0,rect.r1,rect.c0,rect.c1].every(Number.isInteger)||rect.r0<0||rect.c0<0||rect.r1>=this.n||rect.c1>=this.n||rect.r0>rect.r1||rect.c0>rect.c1){this.initialIssues.push({kind:'INVALID_SELECTED_RECT',clue:id,rank:0});continue}let cand=this.candidate(id,rectKey(rect));if(!cand||cand.baseReasons.length){this.initialIssues.push({kind:cand?.baseReasons?.includes('OTHER_CLUE_INSIDE')?'OTHER_CLUE_INSIDE':cand?.baseReasons?.includes('WRONG_AREA')?'WRONG_AREA':cand?.baseReasons?.includes('WRONG_SHAPE')?'WRONG_SHAPE':'INVALID_SELECTED_RECT',clue:id,rectangle:rect,rank:0});continue}if(!this.selected.has(id))this.selected.set(id,this.makeFact('SELECTED_RECT',{clue:id,rect:copy(cand)},{rank:0,source:'player'}))}
  }
  seedMechanicalExclusions(){
    for(const id of this.ids){let union=new Set();for(const c of this.activeCandidates(id))for(const x of c.cells)union.add(cellKey(x));let d=this.domainRank(id);for(let r=0;r<this.n;r++)for(let c=0;c<this.n;c++){let cell=[r,c];if(!union.has(`${r},${c}`)&&this.owner(cell)?.clue!==id)this.addNotOwner(cell,id,{rank:d.rank,dependencies:d.dependencies,source:'domain'})}}
  }
  addOwner(cell,id,meta={}){let k=cellKey(cell),old=this.ownerFacts.get(k);if(old){if(old.clue===id)return old;this.initialIssues.push({kind:'OWNER_CONFLICT',cell:cell.slice(),clues:[old.clue,id],rank:Math.max(old.rank||0,Number(meta.rank)||0)});return null}let f=this.makeFact('OWNER',{cell:cell.slice(),clue:id},meta);this.ownerFacts.set(k,f);return f}
  addNotOwner(cell,id,meta={}){let own=this.owner(cell);if(own?.clue===id){this.initialIssues.push({kind:'OWNER_CONFLICT',cell:cell.slice(),clues:[id],rank:Math.max(own.rank||0,Number(meta.rank)||0)});return null}let k=cellKey(cell)+'|'+id,old=this.notOwnerFacts.get(k);if(old)return old;let f=this.makeFact('NOT_OWNER',{cell:cell.slice(),clue:id},meta);this.notOwnerFacts.set(k,f);return f}
  eliminateCandidate(id,key,meta={}){let c=this.candidate(id,key);if(!c||!c.active)return false;c.active=false;c.elimination={rule:meta.rule||'RECTANGLE_DOMAIN',reason:meta.reason||null,reasons:meta.reasons||null,rank:Number(meta.rank)||0,dependencies:uniq(meta.dependencies||[]),deductionId:meta.deductionId||null,source:meta.source||'deduction'};this.activeCandidatesCache.delete(id);this.domainPremiseCache.delete(id);return true}
  refreshDomains(meta={}){
    let changed=false;for(const id of this.ids){let selected=this.selected.get(id);for(const c of this.candidates.get(id)||[]){if(!c.active)continue;let reason=null,premises=[];
      if(selected&&c.key!==selected.rect.key){reason='FORBIDDEN_CELL_INCLUDED';premises.push(this.factPremise(selected))}
      if(!reason){for(const f of this.ownerFacts.values()){if(f.clue===id&&!rectHas(c,f.cell)){reason='REQUIRED_CELL_MISSING';premises.push(this.factPremise(f));break}if(f.clue!==id&&rectHas(c,f.cell)){reason='FORBIDDEN_CELL_INCLUDED';premises.push(this.factPremise(f));break}}}
      if(!reason){for(const f of this.notOwnerFacts.values())if(f.clue===id&&rectHas(c,f.cell)){reason='FORBIDDEN_CELL_INCLUDED';premises.push(this.factPremise(f));break}}
      if(!reason){for(const [other,s] of this.selected)if(other!==id&&rectOverlap(c,s.rect)){reason='OVERLAPS_SELECTED_RECT';premises.push(this.factPremise(s));break}}
      if(reason){let rank=Math.max(Number(meta.rank)||0,maxRank(premises));let deps=uniq((meta.dependencies||[]).concat(premises.flatMap(p=>p?.dependencies||[])));changed=this.eliminateCandidate(id,c.key,{rule:'RECTANGLE_DOMAIN',reason,rank,dependencies:deps,deductionId:meta.deductionId,source:'propagation'})||changed}
    }}return changed
  }
  makeDeduction(rule,premises,focusCells,focusClues,focusRectangles,conclusions,explanationData={},priority=null){premises=(premises||[]).filter(Boolean);let cost=RULE_COST[rule]??1,rank=maxRank(premises)+cost,level=RULE_LEVEL[rule]??1,cs=(conclusions||[]).map(c=>({...copy(c),rank})),deps=uniq(premises.flatMap(p=>p.dependencies||[])),signature=rule+'|'+cs.map(c=>c.type==='OWNER'?`O:${cellKey(c.cell)}=${c.clue}`:c.type==='NOT_OWNER'?`N:${cellKey(c.cell)}!=${c.clue}`:c.type==='SELECTED_RECT'?`S:${c.clue}=${c.rectangle.key||rectKey(c.rectangle)}`:`E:${c.clue}=${c.rectangleKey}`).join(';');return {schema:1,id:'candidate:'+signature,signature,rule,ruleCost:cost,rank,techniqueLevel:level,techniqueKey:'T'+level,premises:copy(premises),dependencies:deps,focusCells:uniqCells(focusCells),focusClues:uniq(focusClues),focusRectangles:copy(focusRectangles||[]),conclusions:cs,explanationData:copy(explanationData||{}),priority:priority==null?(RULE_PRIORITY[rule]??50):priority}}
  syncCommonExclusions(meta={}){let changed=false,newFacts=[];for(const id of this.ids){let active=this.activeCandidates(id),union=new Set();for(const c of active)for(const x of c.cells)union.add(cellKey(x));let d=this.domainRank(id),rank=Math.max(Number(meta.rank)||0,d.rank),deps=uniq((meta.dependencies||[]).concat(d.dependencies));for(let r=0;r<this.n;r++)for(let c=0;c<this.n;c++){let cell=[r,c];if(union.has(cellKey(cell))||this.notOwner(cell,id)||this.owner(cell)?.clue===id)continue;let f=this.addNotOwner(cell,id,{rank,dependencies:deps,deductionId:meta.deductionId,source:'domain'});if(f){changed=true;newFacts.push(f)}}}return {changed,newFacts}}
  selectCandidate(id,rect,meta={}){let key=rect.key||rectKey(rect),cand=this.candidate(id,key);if(!cand||!cand.active)return null;let old=this.selected.get(id);if(old)return old.rect.key===key?old:null;let f=this.makeFact('SELECTED_RECT',{clue:id,rect:copy(cand)},meta);this.selected.set(id,f);return f}
  applyConclusion(c,meta={}){if(c.type==='OWNER')return this.addOwner(c.cell,c.clue,meta);if(c.type==='NOT_OWNER')return this.addNotOwner(c.cell,c.clue,meta);if(c.type==='SELECTED_RECT')return this.selectCandidate(c.clue,c.rectangle,meta);if(c.type==='ELIMINATED_CANDIDATE')return this.eliminateCandidate(c.clue,c.rectangleKey,meta);return null}
  propagationAfterConclusion(c,meta={}){
    let automatic=[];
    if(c.type==='SELECTED_RECT'){
      let id=c.clue,sel=this.selected.get(id);if(!sel)return automatic;let ps=[this.factPremise(sel)],conclusions=[];
      for(const cell of sel.rect.cells){let old=this.owner(cell);if(!old){let f=this.addOwner(cell,id,meta);if(f)conclusions.push({type:'OWNER',cell:cell.slice(),clue:id,rank:Number(meta.rank)||0})}}
      for(const cand of this.candidates.get(id)||[])if(cand.active&&cand.key!==sel.rect.key){if(this.eliminateCandidate(id,cand.key,{rule:'RECTANGLE_PROPAGATION',reason:'OTHER_CANDIDATE_OF_SELECTED_CLUE',rank:meta.rank,dependencies:meta.dependencies,deductionId:meta.deductionId}))conclusions.push({type:'ELIMINATED_CANDIDATE',clue:id,rectangleKey:cand.key,rank:Number(meta.rank)||0})}
      for(const other of this.ids)if(other!==id)for(const cand of this.activeCandidates(other))if(rectOverlap(sel.rect,cand)){if(this.eliminateCandidate(other,cand.key,{rule:'RECTANGLE_PROPAGATION',reason:'OVERLAPS_SELECTED_RECT',rank:meta.rank,dependencies:meta.dependencies,deductionId:meta.deductionId}))conclusions.push({type:'ELIMINATED_CANDIDATE',clue:other,rectangleKey:cand.key,rank:Number(meta.rank)||0})}
      if(conclusions.length)automatic.push(this.makeDeduction('RECTANGLE_PROPAGATION',ps,sel.rect.cells,[id],[sel.rect],conclusions,{selected:keyOrRect(sel.rect)},0))
    }
    if(c.type==='OWNER'||c.type==='NOT_OWNER'){
      let before=new Map(this.ids.map(id=>[id,new Set(this.activeCandidateKeys(id))]));this.refreshDomains(meta);let eliminated=[];for(const id of this.ids){let after=new Set(this.activeCandidateKeys(id));for(const key of before.get(id))if(!after.has(key))eliminated.push({type:'ELIMINATED_CANDIDATE',clue:id,rectangleKey:key,rank:Number(meta.rank)||0})}if(eliminated.length){let f=c.type==='OWNER'?this.owner(c.cell):this.notOwner(c.cell,c.clue);automatic.push(this.makeDeduction('OWNERSHIP_PROPAGATION',[this.factPremise(f)],[c.cell],[c.clue],[],eliminated,{},0))}
    }
    return automatic
  }
  _applyDeduction(d,close=true){if(!d)return {deduction:null,automatic:[]};let real=copy(d);real.id='D'+(++this.dedSeq);real.dependencies=uniq(real.dependencies||[]);let meta={rank:real.rank,dependencies:uniq((real.dependencies||[]).concat(real.id)),deductionId:real.id,source:'deduction'},automatic=[];for(const c of real.conclusions||[]){this.applyConclusion(c,meta);automatic.push(...this.propagationAfterConclusion(c,meta))}this.refreshDomains(meta);let ex=this.syncCommonExclusions(meta);if(ex.changed)this.refreshDomains(meta);this.appliedDeductions.push(real);if(close){let c=this.closeCost0(meta);automatic.push(...c.automatic);if(c.contradiction)return {deduction:real,automatic,contradiction:c.contradiction}}return {deduction:real,automatic}}
  applyDeduction(d){return this._applyDeduction(d,true)}
  closeCost0(parentMeta={}){let automatic=[],guard=0;while(guard++<this.n*this.n*this.ids.length*3){let bad=this.diagnoseBasic();if(bad)return {automatic,contradiction:bad};let d=this.cost0Deductions()[0];if(!d)break;let a=this._applyDeduction(d,false);if(!a.deduction)break;automatic.push(a.deduction,...a.automatic);this.refreshDomains({rank:a.deduction.rank,dependencies:[a.deduction.id],deductionId:a.deduction.id});this.syncCommonExclusions({rank:a.deduction.rank,dependencies:[a.deduction.id],deductionId:a.deduction.id})}return {automatic,contradiction:this.diagnoseBasic()}}
  diagnoseBasic(){
    if(this.initialIssues.length)return copy(this.initialIssues[0]);
    for(const [k,f] of this.ownerFacts){for(const id of this.ids)if(id!==f.clue){let g=this.ownerFacts.get(k);if(g&&g.clue!==f.clue)return {kind:'OWNER_CONFLICT',cell:f.cell.slice(),clues:[f.clue,g.clue],rank:Math.max(f.rank||0,g.rank||0)}}}
    let sels=[...this.selected.entries()];for(let i=0;i<sels.length;i++)for(let j=i+1;j<sels.length;j++)if(rectOverlap(sels[i][1].rect,sels[j][1].rect))return {kind:'SELECTED_OVERLAP',clues:[sels[i][0],sels[j][0]],rectangles:[copy(sels[i][1].rect),copy(sels[j][1].rect)],rank:Math.max(sels[i][1].rank||0,sels[j][1].rank||0)};
    for(const id of this.ids){let clue=this.clues[id],owners=[...this.ownerFacts.values()].filter(f=>f.clue===id),box=rectFromCells(owners.map(f=>f.cell));if(box&&clue.area!=null){let area=(box.r1-box.r0+1)*(box.c1-box.c0+1);if(area>clue.area)return {kind:'AREA_OVERFLOW',clue:id,area,requiredArea:clue.area,cells:owners.map(f=>f.cell),rank:maxRank(owners)}}let active=this.activeCandidates(id);if(!active.length){let p=this.domainPremise(id),all=this.candidates.get(id)||[],shapeImpossible=!!clue.shape&&!all.some(c=>!c.baseReasons.includes('WRONG_SHAPE')&&!c.baseReasons.includes('WRONG_AREA'));return {kind:shapeImpossible?'SHAPE_IMPOSSIBLE':'NO_CANDIDATE_FOR_CLUE',clue:id,premises:[p],rank:p.rank}}}
    for(let r=0;r<this.n;r++)for(let c=0;c<this.n;c++){let cell=[r,c],own=this.owner(cell);if(own)continue;let support=false;for(const id of this.ids)if(this.activeCandidates(id).some(x=>rectHas(x,cell))){support=true;break}if(!support){let ps=this.ids.map(id=>this.domainPremise(id));return {kind:'NO_COVER_FOR_CELL',cell,premises:ps,rank:maxRank(ps)}}}
    return this.diagnoseCapacity()||this.diagnoseLocal()||null
  }
  commonCoverageDeductions(){let out=[];for(const id of this.ids){let active=this.activeCandidates(id);if(active.length<2)continue;let common=new Set(active[0].cells.map(cellKey));for(const k of [...common])if(!active.every(c=>c.cells.some(x=>cellKey(x)===k)))common.delete(k);let cells=[...common].map(k=>k.split(',').map(Number)).filter(cell=>this.owner(cell)?.clue!==id);if(cells.length){let p=this.domainPremise(id);out.push(this.makeDeduction('COMMON_COVERAGE',[p],cells.concat([this.clues[id].pos]),[id],active.slice(0,8),cells.map(cell=>({type:'OWNER',cell,clue:id})),{candidateCount:active.length,commonCells:cells},10))}}return out.sort(deductionComparator)}
  cellLockedDeductions(){let out=[];for(let r=0;r<this.n;r++)for(let c=0;c<this.n;c++){let cell=[r,c];if(this.owner(cell))continue;let owners=[];for(const id of this.ids)if(this.activeCandidates(id).some(x=>rectHas(x,cell)))owners.push(id);if(owners.length!==1)continue;let id=owners[0],supports=this.activeCandidates(id).filter(x=>rectHas(x,cell));if(supports.length<2)continue;let ps=this.ids.map(x=>this.domainPremise(x));out.push(this.makeDeduction('CELL_LOCKED_TO_CLUE',ps,[cell,this.clues[id].pos],[id],supports.slice(0,8),[{type:'OWNER',cell,clue:id}],{cell,clue:id,supportCount:supports.length},20))}return out.sort(deductionComparator)}
  coverageLockedSetDeductions(){let out=[],eligible=this.ids.filter(id=>!this.selected.has(id)||this.activeCandidates(id).length===1).slice(0,this.options.maxLockedSetClues);for(let k=2;k<=Math.min(this.options.maxLockedSetSize,eligible.length);k++)for(const group of combinations(eligible,k)){let union=new Set(),mins=[],ps=[];for(const id of group){let a=this.activeCandidates(id);if(!a.length){mins=[];break}mins.push(Math.min(...a.map(x=>x.area)));ps.push(this.domainPremise(id));for(const cand of a)for(const cell of cand.cells)union.add(cellKey(cell))}if(!mins.length)continue;let required=mins.reduce((a,b)=>a+b,0);if(required!==union.size)continue;let conclusions=[],focus=[...union].map(k=>k.split(',').map(Number));for(const other of this.ids)if(!group.includes(other))for(const cell of focus)if(!this.notOwner(cell,other)&&this.owner(cell)?.clue!==other)conclusions.push({type:'NOT_OWNER',cell:cell.slice(),clue:other});if(!conclusions.length)continue;out.push(this.makeDeduction('COVERAGE_LOCKED_SET',ps,focus,group,[],conclusions,{group:group.slice(),minAreas:mins,requiredMinimum:required,unionSize:union.size},30));if(out.length>=8)return out.sort(deductionComparator)}return out.sort(deductionComparator)}
  noSupportClueDeductions(){let out=[];for(const a of this.ids){let ac=this.activeCandidates(a);if(ac.length<2)continue;for(const cand of ac){for(const b of this.ids){if(b===a)continue;let bc=this.activeCandidates(b);if(!bc.length||!bc.every(x=>rectOverlap(cand,x)))continue;let ps=[this.domainPremise(a),this.domainPremise(b)];out.push(this.makeDeduction('NO_SUPPORT_CLUE',ps,cand.cells.concat([this.clues[b].pos]),[a,b],[cand].concat(bc.slice(0,6)),[{type:'ELIMINATED_CANDIDATE',clue:a,rectangleKey:cand.key}],{clue:a,rectangleKey:cand.key,blockedClue:b,blockedCandidateCount:bc.length},40));break}if(out.length>=8)return out.sort(deductionComparator)}}return out.sort(deductionComparator)}
  candidateLeavesCellUnsupported(a,cand){let witness=null;for(let r=0;r<this.n&&!witness;r++)for(let c=0;c<this.n;c++){let cell=[r,c];if(rectHas(cand,cell))continue;let supported=false;for(const id of this.ids){if(id===a)continue;for(const x of this.activeCandidates(id)){if(rectOverlap(cand,x))continue;if(rectHas(x,cell)){supported=true;break}}if(supported)break}if(!supported){witness=cell;break}}return witness}
  noSupportCellDeductions(){let out=[];for(const a of this.ids){let ac=this.activeCandidates(a);if(ac.length<2)continue;for(const cand of ac){let cell=this.candidateLeavesCellUnsupported(a,cand);if(!cell)continue;let ps=[this.domainPremise(a)].concat(this.ids.filter(id=>id!==a).map(id=>this.domainPremise(id)));out.push(this.makeDeduction('NO_SUPPORT_CELL',ps,cand.cells.concat([cell]),[a],[cand],[{type:'ELIMINATED_CANDIDATE',clue:a,rectangleKey:cand.key}],{clue:a,rectangleKey:cand.key,unsupportedCell:cell},45));if(out.length>=8)return out.sort(deductionComparator)}}return out.sort(deductionComparator)}
  localGroupCombinations(group,limit=this.options.maxLocalCandidates){let domains=group.map(id=>this.activeCandidates(id));if(domains.some(a=>!a.length))return [];let total=domains.reduce((p,a)=>p*a.length,1);if(total>limit)return null;let out=[];function go(i,picked){if(i===group.length){out.push(picked.slice());return}for(const cand of domains[i]){if(picked.some(x=>rectOverlap(x.cand,cand)))continue;picked.push({id:group[i],cand});go(i+1,picked);picked.pop()}}go(0,[]);return out}
  localDomainSupportDeductions(){let out=[],ids=this.ids.filter(id=>this.activeCandidates(id).length>1&&this.activeCandidates(id).length<=12);for(let k=2;k<=Math.min(this.options.maxLocalGroupSize,ids.length);k++)for(const group of combinations(ids,k)){let combos=this.localGroupCombinations(group);if(combos==null||!combos.length)continue;let ps=group.map(id=>this.domainPremise(id));for(const id of group){for(const cand of this.activeCandidates(id)){if(combos.some(combo=>combo.some(x=>x.id===id&&x.cand.key===cand.key)))continue;out.push(this.makeDeduction('LOCAL_DOMAIN_SUPPORT',ps,cand.cells,group,[cand],[{type:'ELIMINATED_CANDIDATE',clue:id,rectangleKey:cand.key}],{group:group.slice(),combinationCount:combos.length,unsupportedCandidate:{clue:id,rectangleKey:cand.key}},60));if(out.length>=6)return out.sort(deductionComparator)}}for(let r=0;r<this.n;r++)for(let c=0;c<this.n;c++){let cell=[r,c];if(this.owner(cell))continue;for(const id of group){if(combos.every(combo=>{let x=combo.find(y=>y.id===id);return x&&rectHas(x.cand,cell)})){out.push(this.makeDeduction('LOCAL_DOMAIN_SUPPORT',ps,[cell].concat(group.map(x=>this.clues[x].pos)),group,[],[{type:'OWNER',cell,clue:id}],{group:group.slice(),combinationCount:combos.length,commonOwner:{cell,clue:id}},60));if(out.length>=6)return out.sort(deductionComparator)}}}}return out.sort(deductionComparator)}
  directDeductions(){return [].concat(this.cost0Deductions(),this.commonCoverageDeductions(),this.cellLockedDeductions(),this.coverageLockedSetDeductions(),this.noSupportClueDeductions(),this.noSupportCellDeductions(),this.localDomainSupportDeductions()).sort(deductionComparator)}
  hypothesisResultDetailed(id,rectangleKey,maxSteps=this.options.maxHypothesisSteps){
    let cand=this.candidate(id,rectangleKey);if(!cand||!cand.active)return {contradiction:{kind:'ELIMINATED_CANDIDATE',clue:id,rectangleKey},trace:[],session:this.clone(),budgetHit:false};
    let fork=this.clone(),base=this.domainRank(id),meta={rank:base.rank,dependencies:base.dependencies,source:'assumption',hypothesis:true};fork.selectCandidate(id,cand,meta);fork.propagationAfterConclusion({type:'SELECTED_RECT',clue:id,rectangle:copy(cand)},meta);fork.refreshDomains(meta);fork.syncCommonExclusions(meta);let trace=[],closed=fork.closeCost0(meta);trace.push(...closed.automatic);if(closed.contradiction)return {contradiction:closed.contradiction,trace,session:fork,budgetHit:false};
    let limit=Math.max(0,Number(maxSteps)||0),exhausted=true;
    for(let i=0;i<limit;i++){let bad=fork.diagnoseBasic();if(bad)return {contradiction:bad,trace,session:fork,budgetHit:false};let ds=fork.directDeductions().filter(d=>d.ruleCost<=1),d=ds[0];if(!d){exhausted=false;break}let a=fork.applyDeduction(d);if(!a.deduction){exhausted=false;break}trace.push(a.deduction,...a.automatic);if(a.contradiction)return {contradiction:a.contradiction,trace,session:fork,budgetHit:false}}
    let contradiction=fork.diagnoseBasic();if(contradiction)return {contradiction,trace,session:fork,budgetHit:false};
    let budgetHit=exhausted&&!!fork.directDeductions().find(d=>d.ruleCost<=1);return {contradiction:null,trace,session:fork,budgetHit}
  }
  hypothesisResult(id,rectangleKey,maxSteps=this.options.maxHypothesisSteps){let x=this.hypothesisResultDetailed(id,rectangleKey,maxSteps);return {contradiction:x.contradiction,trace:x.trace,session:x.session}}
  witnessPremises(w,id){if(Array.isArray(w?.premises)&&w.premises.length)return copy(w.premises);let clues=[];if(w?.clue!=null)clues.push(w.clue);if(Array.isArray(w?.clues))clues.push(...w.clues);if(!clues.length&&id!=null)clues.push(id);if(w?.kind==='NO_COVER_FOR_CELL')clues=this.ids.slice();return uniq(clues).map(x=>this.domainPremise(x))}
  contradictionDeduction(id,rectangleKey,result){let cand=this.candidate(id,rectangleKey),w=copy(result.contradiction),ps=this.witnessPremises(w,id);ps.unshift({kind:'ASSUMPTION',clue:id,rectangleKey,rank:0,dependencies:[],hypothesis:true});return this.makeDeduction('ASSUMPTION_CONTRADICTION',ps,uniqCells((cand?.cells||[]).concat(w?.cells||[],w?.cell?[w.cell]:[])),uniq([id].concat(w?.clue!=null?[w.clue]:w?.clues||[])),cand?[cand]:[],[{type:'ELIMINATED_CANDIDATE',clue:id,rectangleKey}],{assumption:{clue:id,rectangleKey},witness:w,trace:(result.trace||[]).map(copy),causalTrace:causalTraceForWitness(result.trace||[],w)},90)}
  assumptionContradictionsDetailed(limit=6){let out=[],budgetHit=false,ordered=this.ids.slice().sort((a,b)=>this.activeCandidates(a).length-this.activeCandidates(b).length);for(const id of ordered){let active=this.activeCandidates(id);if(active.length<2||active.length>this.options.maxHypothesisCandidates)continue;for(const cand of active){let r=this.hypothesisResultDetailed(id,cand.key);if(r.budgetHit){budgetHit=true;continue}if(r.contradiction){out.push(this.contradictionDeduction(id,cand.key,r));if(out.length>=limit)return {deductions:out.sort(deductionComparator),budgetHit}}}}return {deductions:out.sort(deductionComparator),budgetHit}}
  assumptionContradictions(limit=6){let out=[],ordered=this.ids.slice().sort((a,b)=>this.activeCandidates(a).length-this.activeCandidates(b).length);for(const id of ordered){let active=this.activeCandidates(id);if(active.length<2||active.length>this.options.maxHypothesisCandidates)continue;for(const cand of active){let r=this.hypothesisResult(id,cand.key);if(r.contradiction){out.push(this.contradictionDeduction(id,cand.key,r));if(out.length>=limit)return out.sort(deductionComparator)}}}return out.sort(deductionComparator)}
  branchNewOwners(result){let out=new Map();for(const f of result.session.ownerFacts.values()){let base=this.owner(f.cell);if(!base)out.set(cellKey(f.cell),{type:'OWNER',cell:f.cell.slice(),clue:f.clue});else if(base.clue!==f.clue)return null}return out}
  commonConsequencesDetailed(limit=4){let out=[],budgetHit=false,ordered=this.ids.slice().sort((a,b)=>this.activeCandidates(a).length-this.activeCandidates(b).length);for(const id of ordered){let active=this.activeCandidates(id);if(active.length<2||active.length>this.options.maxHypothesisCandidates)continue;let branches=active.map(c=>({cand:c,result:this.hypothesisResultDetailed(id,c.key,this.options.maxCommonSteps)}));if(branches.some(x=>x.result.budgetHit)){budgetHit=true;continue}if(branches.some(x=>x.result.contradiction))continue;let common=null;for(const b of branches){let m=this.branchNewOwners(b.result);if(!m){common=null;break}if(common==null)common=m;else for(const k of [...common.keys()]){let x=common.get(k),y=m.get(k);if(!y||y.clue!==x.clue)common.delete(k)}}if(!common?.size)continue;for(const fact of common.values()){if(this.owner(fact.cell))continue;let branchPremises=branches.map(b=>{let f=b.result.session.owner(fact.cell),traceRank=Math.max(0,...(b.result.trace||[]).map(d=>Number(d.rank)||0)),rank=Math.max(traceRank,Number(f?.rank)||0);return {kind:'BRANCH_DERIVATION',clue:id,rectangleKey:b.cand.key,conclusion:{type:'OWNER',cell:fact.cell.slice(),clue:fact.clue},rank,dependencies:uniq((f?.dependencies||[]).concat((b.result.trace||[]).flatMap(d=>d.dependencies||[])))}}),ps=[this.domainPremise(id),...branchPremises];out.push(this.makeDeduction('COMMON_CONSEQUENCE',ps,uniqCells([this.clues[id].pos,fact.cell]),[id,fact.clue],active.slice(),[fact],{branchClue:id,alternatives:active.map(x=>x.key),commonOwner:copy(fact),traces:branches.map(b=>({rectangleKey:b.cand.key,trace:b.result.trace.map(copy),causalTrace:causalTraceForConclusion(b.result.trace,fact)}))},100));if(out.length>=limit)return {deductions:out.sort(deductionComparator),budgetHit}}}return {deductions:out.sort(deductionComparator),budgetHit}}
  commonConsequences(limit=4){let out=[],ordered=this.ids.slice().sort((a,b)=>this.activeCandidates(a).length-this.activeCandidates(b).length);for(const id of ordered){let active=this.activeCandidates(id);if(active.length<2||active.length>this.options.maxHypothesisCandidates)continue;let branches=active.map(c=>({cand:c,result:this.hypothesisResult(id,c.key,this.options.maxCommonSteps)}));if(branches.some(x=>x.result.contradiction))continue;let common=null;for(const b of branches){let m=this.branchNewOwners(b.result);if(!m){common=null;break}if(common==null)common=m;else for(const k of [...common.keys()]){let x=common.get(k),y=m.get(k);if(!y||y.clue!==x.clue)common.delete(k)}}if(!common?.size)continue;for(const fact of common.values()){if(this.owner(fact.cell))continue;let branchPremises=branches.map(b=>{let f=b.result.session.owner(fact.cell),traceRank=Math.max(0,...(b.result.trace||[]).map(d=>Number(d.rank)||0)),rank=Math.max(traceRank,Number(f?.rank)||0);return {kind:'BRANCH_DERIVATION',clue:id,rectangleKey:b.cand.key,conclusion:{type:'OWNER',cell:fact.cell.slice(),clue:fact.clue},rank,dependencies:uniq((f?.dependencies||[]).concat((b.result.trace||[]).flatMap(d=>d.dependencies||[])))}}),ps=[this.domainPremise(id),...branchPremises];out.push(this.makeDeduction('COMMON_CONSEQUENCE',ps,uniqCells([this.clues[id].pos,fact.cell]),[id,fact.clue],active.slice(),[fact],{branchClue:id,alternatives:active.map(x=>x.key),commonOwner:copy(fact),traces:branches.map(b=>({rectangleKey:b.cand.key,trace:b.result.trace.map(copy),causalTrace:causalTraceForConclusion(b.result.trace,fact)}))},100));if(out.length>=limit)return out.sort(deductionComparator)}}return out.sort(deductionComparator)}
  nextDeductionDetailed(){let contradiction=this.diagnoseBasic();if(contradiction)return {contradiction,budgetHit:false};let direct=this.directDeductions();if(direct.length)return {deduction:direct[0],budgetHit:false};let a=this.assumptionContradictionsDetailed();if(a.deductions.length)return {deduction:a.deductions[0],budgetHit:false};let c=this.commonConsequencesDetailed();if(c.deductions.length)return {deduction:c.deductions[0],budgetHit:false};return {deduction:null,budgetHit:!!(a.budgetHit||c.budgetHit)}}
  nextDeduction(){let x=this.nextDeductionDetailed();return x.contradiction?{contradiction:x.contradiction}:{deduction:x.deduction||null}}
  proveOwner(cell,id){let own=this.owner(cell);if(own)return {status:own.clue===id?'proven':'incorrect',fact:copy(own)};if(this.notOwner(cell,id))return {status:'incorrect',fact:copy(this.notOwner(cell,id))};let bad=this.diagnoseBasic();if(bad)return {status:'contradictory',contradiction:copy(bad)};let direct=this.directDeductions().filter(d=>(d.conclusions||[]).some(c=>c.type==='OWNER'&&sameCell(c.cell,cell)&&c.clue===id));if(direct.length)return {status:'proven',deduction:direct.sort(deductionComparator)[0]};return {status:'not-yet-proven'}}
  proveRectangle(id,rect){let key=typeof rect==='string'?rect:rectKey(rect),cand=this.candidate(id,key);if(!cand)return {status:'incorrect',contradiction:{kind:'INVALID_SELECTED_RECT',clue:id,rectangleKey:key}};if(cand.baseReasons?.length)return {status:'incorrect',contradiction:{kind:cand.baseReasons[0],clue:id,rectangleKey:key,reasons:cand.baseReasons.slice()}};let selected=this.selected.get(id);if(selected)return {status:selected.rect.key===key?'proven':'incorrect',fact:copy(selected)};let bad=this.diagnoseBasic();if(bad)return {status:'contradictory',contradiction:copy(bad)};if(!cand.active)return {status:'contradictory',contradiction:{kind:'ELIMINATED_CANDIDATE',clue:id,rectangleKey:key,elimination:copy(cand.elimination)}};let direct=this.directDeductions().filter(d=>(d.conclusions||[]).some(c=>c.type==='SELECTED_RECT'&&c.clue===id&&(c.rectangle.key||rectKey(c.rectangle))===key));if(direct.length)return {status:'proven',deduction:direct.sort(deductionComparator)[0]};return {status:'not-yet-proven'}}
  metrics(){let counts={},maxRank=0,maxTechniqueLevel=0;for(const d of this.appliedDeductions){counts[d.rule]=(counts[d.rule]||0)+1;maxRank=Math.max(maxRank,d.rank||0);maxTechniqueLevel=Math.max(maxTechniqueLevel,d.techniqueLevel||0)}return {maxRank,maxTechniqueLevel,deductionsByRule:counts,countCommonCoverage:counts.COMMON_COVERAGE||0,countCellLocked:counts.CELL_LOCKED_TO_CLUE||0,countCoverageLockedSet:counts.COVERAGE_LOCKED_SET||0,countNoSupport:(counts.NO_SUPPORT_CLUE||0)+(counts.NO_SUPPORT_CELL||0),countLocalDomain:counts.LOCAL_DOMAIN_SUPPORT||0,countContradiction:counts.ASSUMPTION_CONTRADICTION||0,countCommonConsequence:counts.COMMON_CONSEQUENCE||0}}
  diagnoseCapacity(){let eligible=this.ids.slice(0,this.options.maxLockedSetClues);for(let k=2;k<=Math.min(this.options.maxLockedSetSize,eligible.length);k++)for(const group of combinations(eligible,k)){let union=new Set(),mins=[],ps=[];for(const id of group){let a=this.activeCandidates(id);if(!a.length){mins=[];break}mins.push(Math.min(...a.map(x=>x.area)));ps.push(this.domainPremise(id));for(const cand of a)for(const cell of cand.cells)union.add(cellKey(cell))}if(!mins.length)continue;let required=mins.reduce((a,b)=>a+b,0);if(required>union.size)return {kind:'COVERAGE_DEFICIT',clues:group.slice(),requiredMinimum:required,unionSize:union.size,cells:[...union].map(k=>k.split(',').map(Number)),premises:ps,rank:maxRank(ps)}}return null}
  diagnoseLocal(){let ids=this.ids.filter(id=>this.activeCandidates(id).length>1&&this.activeCandidates(id).length<=10);for(let k=2;k<=Math.min(this.options.maxLocalGroupSize,ids.length);k++)for(const group of combinations(ids,k)){let combos=this.localGroupCombinations(group);if(Array.isArray(combos)&&!combos.length){let ps=group.map(id=>this.domainPremise(id));return {kind:'NO_LOCAL_COMPLETION',clues:group.slice(),premises:ps,rank:maxRank(ps)}}}return null}
  cost0Deductions(){
    let out=[];
    for(const id of this.ids){if(this.selected.has(id))continue;let active=this.activeCandidates(id);if(active.length===1){let p=this.domainPremise(id),r=active[0],clue=this.clues[id],areaDimensions=[],shapeDimensions=[],reasonCounts={};if(clue.area!=null)for(let h=1;h<=this.n;h++)for(let w=1;w<=this.n;w++)if(h*w===clue.area){areaDimensions.push([h,w]);if(!clue.shape||shapeOf(h,w)===clue.shape)shapeDimensions.push([h,w])}for(const c of this.candidates.get(id)||[])if(!c.active&&c.elimination?.reason)reasonCounts[c.elimination.reason]=(reasonCounts[c.elimination.reason]||0)+1;out.push(this.makeDeduction('CLUE_SINGLETON',[p],r.cells,[id],[r],[{type:'SELECTED_RECT',clue:id,rectangle:copy(r)}],{remaining:1,constraints:{area:clue.area,shape:clue.shape},areaDimensions,shapeDimensions,reasonCounts,remainingRectangle:keyOrRect(r)},0))}}
    // Any uncovered cell with exactly one (clue,candidate) support selects that rectangle.
    for(let r=0;r<this.n;r++)for(let c=0;c<this.n;c++){let cell=[r,c],owner=this.owner(cell);if(owner)continue;let supports=[];for(const id of this.ids)for(const cand of this.activeCandidates(id))if(rectHas(cand,cell))supports.push([id,cand]);if(supports.length===1){let [id,cand]=supports[0],ps=this.ids.map(x=>this.domainPremise(x));out.push(this.makeDeduction('CELL_SINGLETON',ps,[cell].concat(cand.cells),[id],[cand],[{type:'SELECTED_RECT',clue:id,rectangle:copy(cand)}],{cell:cell.slice()},5))}}
    // Rectangular closure from existing owners.
    for(const id of this.ids){let fs=[...this.ownerFacts.values()].filter(f=>f.clue===id);if(fs.length<2)continue;let box=rectFromCells(fs.map(f=>f.cell)),missing=rectCells(box).filter(x=>!this.owner(x));if(missing.length){let ps=fs.map(f=>this.factPremise(f));out.push(this.makeDeduction('RECTANGULAR_CLOSURE',ps,rectCells(box),[id],[box],missing.map(cell=>({type:'OWNER',cell,clue:id})),{box},8))}
      let clue=this.clues[id];if(clue.area!=null&&((box.r1-box.r0+1)*(box.c1-box.c0+1)===clue.area)&&!this.selected.has(id)){let matching=this.activeCandidates(id).find(x=>x.r0===box.r0&&x.r1===box.r1&&x.c0===box.c0&&x.c1===box.c1);if(matching){let ps=fs.map(f=>this.factPremise(f));out.push(this.makeDeduction('AREA_COMPLETION',ps,matching.cells,[id],[matching],[{type:'SELECTED_RECT',clue:id,rectangle:copy(matching)}],{area:clue.area,box},9))}}
    }
    return out.sort(deductionComparator)
  }
}

function createSession(board,options){return new Session(board,options)}
root.PatchesLogic={VERSION:1,RULE_COST,TECHNIQUE_LEVEL,createSession,Session,deductionComparator,helpers:{shapeOf,normalizeShape,clueConstraints,rectKey,rectCells,rectOverlap},_test:{normalizeBoard,combinations}};
if(typeof module!=='undefined'&&module.exports)module.exports=root.PatchesLogic;
})(typeof globalThis!=='undefined'?globalThis:this);
